# Generated by Django 5.2 on 2025-04-23 03:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='fornecedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produtos_fornecidos', to='estoque.fornecedor'),
        ),
        migrations.AddField(
            model_name='produto',
            name='localizacao',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
